# Generated by Django 2.1.4 on 2018-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('grey', models.IntegerField()),
            ],
        ),
    ]
