# Generated by Django 2.1.4 on 2018-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_waterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdata',
            name='blue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='green',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='grey',
            field=models.FloatField(),
        ),
    ]
